# Generated by Django 3.2 on 2023-05-16 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_negotiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiation',
            name='user',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.buyer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negotiation',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.seller'),
            preserve_default=False,
        ),
    ]
