# Generated by Django 3.2 on 2023-05-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230517_0122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Negotiation',
        ),
    ]
