# Generated by Django 3.2 on 2023-05-16 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_negotiation_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
