# Generated by Django 3.2 on 2023-05-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_negotiation_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.buyer')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.crop')),
            ],
        ),
    ]
